### ISSUE TITLE
Add functionality for making conversation connected to a building

### ISSUE THREAD

**Issue by MBarjaktarovic** [execom-eu/building_manager#7]
Add `NotifyTenantsCommand` to `BulidingManager` and the `TenantsNotifiedEvent` that the command will create.
Add `notifyTenants` method to `/buildings/{id}/tenants` endpoint where the command will be generated.
Add unit tests.

**Comment by millevlada** [comment]
done (fetching conversations for a building is out of scope here since it would be part of other issue that is already created - overview issues)
